version: '3.7'

services:
  database:
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: sprint-retrospective
      MONGO_DATA_DIR: /var/lib/mongodb
    volumes:
      - data-mongo:/var/lib/mongodb
    restart: always
    healthcheck:
      test: mongo --eval 'db.runCommand("ping").ok' --quiet
      interval: 1s
      timeout: 2s
      retries: 10

  redis:
    image: 'redis'
    restart: always
    ports:
      - '6379'
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 2s
      retries: 10

  api:
    build: https://github.com/RobinJ1995/sprint-retrospective-server.git
    image: robinj/sprintretrospective-api
    ports:
      - 5432:5432
    environment:
      DB_HOST: 'database'
      REDIS_URL: 'redis://redis'
      WEBSOCKET_PUBLIC_BASE_URL: 'ws://localhost:5433/'
      PORT: 5432
      ADMIN_KEY: 'i_am_root'
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      websocket:
        condition: service_healthy
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5432/health
      interval: 1s
      timeout: 2s
      retries: 10

  websocket:
    build: https://github.com/RobinJ1995/sprint-retrospective-websocket-server.git
    image: robinj/sprintretrospective-websocket-server
    ports:
      - 5433:5433
    environment:
      REDIS_URL: 'redis://redis'
      PORT: 5433
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    healthcheck:
      test: curl http://localhost:5433/
      interval: 1s
      timeout: 2s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: /app
    environment:
      API_ENDPOINT: 'http://localhost:5432'
      GENERATE_SOURCEMAP: 'false' # Because Docker on MacOS is a shit show
      HOST: "0.0.0.0"
      PORT: "5431"
    ports:
      - 5431:5431
    depends_on:
      api:
        condition: service_healthy
    restart: always
    stdin_open: true
    volumes:
      - ./:/app:z
    command:
      - npm
      - run
      - start
    healthcheck:
      test: curl --fail http://localhost:5431/
      interval: 1s
      timeout: 2s
      retries: 10

volumes:
  data-mongo: