name: Build ARM Docker images

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * *'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --tag docker.pkg.github.com/robinj1995/sprint-retrospective/sprint-retrospective:latest \
            --tag docker.pkg.github.com/robinj1995/sprint-retrospective/sprint-retrospective:${{ github.sha }} ./
      -
        name: Login to GitHub Docker Registry
        uses: crazy-max/ghaction-docker-login@v1
        with:
          registry: docker.pkg.github.com
          username: RobinJ1995
          password: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag docker.pkg.github.com/robinj1995/sprint-retrospective/sprint-retrospective:latest \
            --tag docker.pkg.github.com/robinj1995/sprint-retrospective/sprint-retrospective:${{ github.sha }} ./
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ github.repository }}:${{ github.sha }}
